version: '3'
services:
  shopping_api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8000:8000
  shopping_client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 8080:8080